### ISSUE TITLE
[Enhancement] Allow for RAM overvolting for erista units 

### ISSUE THREAD

**Issue by Anxietytimmy** [KazushiMe/Switch-OC-Suite#10]
Title

**Comment by KazushiMe** [comment]
it is doable but don't hold out hope to overvolting for stability.
might implement simple timing customization for erista later. then you could bump up timings like RAS, trading bandwidth for stability.

**Comment by jbushka** [comment]
Increasing voltage helps a lot with stability on Erista.
In my case, 2064mhz is not stable without atleast 1.2 volts.
Without overvolting that frequency would crash HOS in just 5 seconds, with overvoltage I can play for several hours without any graphic bugs or any other issues.

**Comment by Cooler3D** [comment]
Confirmed. 2133 MHz on Erista need at least 1.2v for stabke work.

**Comment by KazushiMe** [comment]
Solved, and a python script is now added to simplify frequency & voltage customization.
