### ISSUE TITLE
1.2.6.2 crash on erista unit

### ISSUE THREAD

**Issue by zerofalcon** [KazushiMe/Switch-OC-Suite#11]
Hi there, after testing you latest 1.2.6.2 loader kip (without using the loader configurator) the console crash instantly after launching from hekate.
Latest HOS 13.2.1
AMS 1.2.6 EmuMMC
[report_0000000007b5ceee.txt](https://github.com/KazushiMe/Switch-OC-Suite/files/8019114/report_0000000007b5ceee.txt)
p.d renamed the bin to txt report file for github attaching restrictions

**Comment by KazushiMe** [comment]
Fixed and updated in https://github.com/KazushiMe/Switch-OC-Suite/releases/tag/1.2.6.2
