### ISSUE TITLE
Increase CPU Boost

### ISSUE THREAD

**Issue by TeleTubby666** [KazushiMe/Switch-OC-Suite#13]
The ability to set increased CPU- and RAM- speeds permanently causes the default CPU Boost feature to become useless. Since the CPU Boost only remains for a short time, it could be safely increased significantly more (including overvolting). The RAM clock should of course remain unaffected.

**Comment by KazushiMe** [comment]
CPU Boost clock is now configurable via `ldr_config.py` in [1.2.6.3](https://github.com/KazushiMe/Switch-OC-Suite/releases/tag/1.2.6.3).
