### ISSUE TITLE
making handheld-limiting OC optional

### ISSUE THREAD

**Issue by ms2048** [KazushiMe/Switch-OC-Suite#15]
Could you please consider adding an option to not to limit the freqs when in a handheld mode (introduced in 4ff20f1)? I can also help with testing, provided you'd consider implementing it.

I'd really be glad to upgrade without feeling like it is a downgrade of some sort because of these additional limits. The max frequencies are important mainly on emulators, where there really is a night/day difference on some demanding games.

I am currently using AMS 1.2.4 / HOS 13.1.0 with an older version of this mod (that didn't have this limit) on Mariko for a few months now, also recently tried it on a new OLED model, with no adverse effects on a battery or really anything noticeable.

Obviously I understand all the risks involved, etc.

Thank you for this awesome mod!

**Comment by KazushiMe** [comment]
CPU power draw is crazy at anything higher than 1.9 GHz. I have no intention to remove handheld frequencies limits, with the exception of adding another mode exclusively for emulators, where down-clock GPU to compensate for CPU. (CPU unlimited & GPU capped at 460 MHz)

I suppose most emulators don't require GPU > 460 MHz. If my assumption is true, then this will be implemented in next release.

**Comment by KazushiMe** [comment]
CPU capping is removed altogether once "Allow Unsafe Frequencies" is toggled on: https://github.com/KazushiMe/Switch-OC-Suite/releases/tag/1.3.2

|         | Handheld | Charging (USB) | Charging (Official) | Docked |
 |:-------:|:--------:|:--------------:|:-------------------:|:------:|
 | **GPU** | 921      | 1267           | -                   | -      |
