### ISSUE TITLE
1.2.6.3 crash on HOS 14.0 and AMS 1.3.0

### ISSUE THREAD

**Issue by ajbritain4** [KazushiMe/Switch-OC-Suite#16]
Hey all, just reporting 1.2.6.3 causes black screen on boot with HOS 14.0 and AMS 1.3.0 on Erista unit.

Setup working fine previously with HOS 13.2.1 and AMS 1.2.6 on the same console. 

Can't find an error log but if you know where it is happy to link to it.

Thanks!

**Comment by KazushiMe** [comment]
> ### Installation
> 3. Grab `x.x.x_loader.kip` for your Atmosphere version

1.2.6_loader.kip only works with AMS 1.2.6. Recompilation is required if you are upgrading to AMS 1.3.0-pre.

**Comment by ajbritain4** [comment]
Thank you! that’s my bad completely, I’d not made the connection between the loader version number and Atmosphere version number 🤦🏻‍♂️
