### ISSUE TITLE
I am using the oc suite, but I can't compile nx2elf, does anyone provide the build binaries? Thanks, I'm using raspberry pi

### ISSUE THREAD

**Issue by lsp199308** [KazushiMe/Switch-OC-Suite#17]
I am using the oc suite, but I can't compile nx2elf, does anyone provide the build binaries? Thanks, I'm using raspberry pi

**Comment by Cooler3D** [comment]
> I am using the oc suite, but I can't compile nx2elf, does anyone provide the build binaries? Thanks, I'm using raspberry pi

[Sure.](https://cloud.sintez.io/s/Zijb3i8wx7Q2dNa)
