### ISSUE TITLE
CPU Clock problem on docked mode

### ISSUE THREAD

**Issue by NaGaa95** [KazushiMe/Switch-OC-Suite#18]
The CPU Clock go from 1785 to 1020 every second when the switch is docked, not happen when in portable

Here is a video : https://www.youtube.com/shorts/N9VCMDBx9hA

Latest Switch OC Suite release / HOS 14.1.0 / AMS 1.3.1

EDIT : The memory clock is always maxed even on the home menu i need to force 1600Mhz on Sys CLK only on docked mode too

**Comment by KazushiMe** [comment]
The threshold of CPU auto boost mode is 90% in docked mode, and sys-clk overlay is quite heavy on system core. See if disabling auto boost mode in misc menu helps.

MEM clock is set to max in docked mode, which is [expected](https://github.com/KazushiMe/Switch-OC-Suite/blob/926b9016b1cf1df905a04d7a0f6d50e63838703f/Source/Atmosphere/stratosphere/loader/source/oc/ldr_oc_suite.cpp#L1199-1213). In ptm performance config table, 1331.2MHz is replaced with 1600.0MHz, while 1600.0MHz is replaced with maximum frequency.

**Comment by KazushiMe** [comment]
Updated sys-clk-oc has been pushed to release 1.3.1.

The issue is caused by sys-clk resetting to built-in boost frequencies, overriding the values in ptm table.
