### ISSUE TITLE
MemTesterNX screen off

### ISSUE THREAD

**Issue by pixeltester** [KazushiMe/Switch-OC-Suite#19]
Would you be able to add a screen off button to MemTesterNX for long tests on Switch Lite, since we can't dock it? Volume Minus to toggle the screen on and off but keep the tests running would be perfect.

**Comment by KazushiMe** [comment]
https://github.com/KazushiMe/Switch-OC-Suite/commit/fd77dfa6ebc24da97a7a78fe720ba760c49b3d7a

I'm not gonna push silent releases so here is the pre-built binary: [MemTesterNX-backlight-toggle.zip](https://github.com/KazushiMe/Switch-OC-Suite/files/8646909/MemTesterNX-backlight-toggle.zip).

Also the backlight toggle is added to sys-clk-overlay (mainly for SysDVR streaming i guess?):
[sys-clk-overlay.ovl.zip](https://github.com/KazushiMe/Switch-OC-Suite/files/8646924/sys-clk-overlay.ovl.zip).

**Comment by pixeltester** [comment]
That's perfect thanks!
