### ISSUE TITLE
How to determine brand of my RAM?

### ISSUE THREAD

**Issue by MattyXarope** [KazushiMe/Switch-OC-Suite#2]
As you point out, there are several different brands of RAM possible - Samsung, Hynix, or Micron - each of which have different RAM overclock profiles. Is there any easy way of determining the brand of RAM that I have?

**Comment by Reverb9** [comment]
Pretty sure Hekate can tell you that.

**Comment by ms2048** [comment]
it's kind of confusing but on Hekate v5.5.6 the option is under
'Console info' (top bar) -> 'HW & Fuses' (lower left) -> top of right column (orange 'Vendor:' field)

**Comment by MattyXarope** [comment]
Thanks all, closing this issue.
