### ISSUE TITLE
[Feature Request] sys-clk-oc 

### ISSUE THREAD

**Issue by Bladen123** [KazushiMe/Switch-OC-Suite#21]
Hello KazushiMe

May i ask if its possible to get a way to hide to Dangerous High rates of OC in sys-clk-Oc ?
Since my girlfriend overclocked to 2GHz the CPU by mistake and she didnt know that , she just wanted to use sys-tune .
So as a part of Safety would be nice to have a little bit of control over this to show or hide some MHz in the menu .

Thank you have a nice day

**Comment by KazushiMe** [comment]
Adding a toggle that enables/disables unsafe frequencies would be more appropriate for this situation as tesla GUI library is quite limited in functionalities.

**Comment by KazushiMe** [comment]
> have (2) sepparate atmosphere folders and (2) switch/.overlays folders to have both versions of sys-clk

Not possible unless manually recompiling all the components including Atmosphere and Tesla menu.

Unsafe frequencies could be disabled now: https://github.com/KazushiMe/Switch-OC-Suite/releases/tag/1.3.2
