### ISSUE TITLE
system won't boot with loader.kip v1.3.2

### ISSUE THREAD

**Issue by Hitseditor** [KazushiMe/Switch-OC-Suite#23]
hekate version/AMS 1.3.2/HOS 14.1.0 & 14.1.1
After the led of mod chip turns from blue to green, switch keeps blackscreen like it's off. Had to hold power button to turn it off.
Removing kip1=atmosphere/kips/loader.kip makes switch bootable, but the OC won't work.
Downgrade AMS and OC-Suite to 1.3.1 and everything works like expected.

**Comment by KazushiMe** [comment]
Check if your `1.3.2_loader.kip` is broken:
unmodified md5: `0ffd5bde5098b8b1e9a9da37a972b483`

**Comment by Hitseditor** [comment]
the 1.3.2_loader.kip works now. The old loader.kip in 1.3.2 assets was a wrong version. 
Problem fixed, thanks.

**Comment by RebelLion420** [comment]
Hi, I ran into the same issue but the loader.kip I have doesn't appear to be a wrong version? The MD5 matches up and I can only boot to a black screen with the OC enabled
