### ISSUE TITLE
Sys clock is not running. 

### ISSUE THREAD

**Issue by Christchex** [KazushiMe/Switch-OC-Suite#26]
Getting a consistent "sys clk is not running" after configuring this several times over.

1.3.2 HOS and using the modified sys-clk.

The memory tests work fine, but the memory setting and overlay are broken.

**Comment by KazushiMe** [comment]
You are most likely using Erista variants. Modded sys-clk in this repo is intended for Mariko consoles only (See README.md).

**Comment by BanchouBoo** [comment]
I'm getting this issue on Erista even on regular sys-clk

**Comment by KazushiMe** [comment]
Fixed in https://github.com/KazushiMe/Switch-OC-Suite/releases/tag/1.4.0.
