### ISSUE TITLE
Problem backup PCV module

### ISSUE THREAD

**Issue by NaGaa95** [KazushiMe/Switch-OC-Suite#3]
Can't dump the PCV Module from my SYSNAND with the script 
At the step Press A/Power Button to continue when i press power button it exit the script and not dumping the PCV module

Switch Lite HOS 13.0.1 / Latest Atmosphere / TegraExplorer 4.0.1

Thanks

**Comment by KazushiMe** [comment]
Deprecated the messy manual patching method in favor of prebuilt `loader.kip`. You can grab those now.
