### ISSUE TITLE
sys-clk-oc override order

### ISSUE THREAD

**Issue by monstrosities** [KazushiMe/Switch-OC-Suite#31]
I noticed that the sys-clk-oc override order is: temporary > permanent > application > system default

However it seems much more logical for it to be: temporary > application > permanent > system default

That would allow you to set permanent baseline clock for your system to override system defaults but then have game specific overrides if you want to really underclock or overclock specific games.

**Comment by KazushiMe** [comment]
Addressed in 1d7395d. Will post a new release once AMS 1.4.0 is no longer in pre-.

**Comment by monstrosities** [comment]
Excellent, thank you!
