### ISSUE TITLE
sys-clk-oc and ReverseNX-RT improper behavior/bugs

### ISSUE THREAD

**Issue by monstrosities** [KazushiMe/Switch-OC-Suite#33]
sys-clk-oc have ReverseNX-RT-OC don't seem to communicate together properly in some circumstances and it results in some strange behavior.

Example:

1. While in docked mode turn off Sync ReverseNX mode from sys-clk-oc overlay and start the game 
2. When the game is booted open sys-clk-oc overlay and you will see it's now reading handheld config for the game instead of docked
3. Open ReverseNX-RT overlay and it reports and sync mode is turned on, even though it's off

**Comment by KazushiMe** [comment]
https://github.com/KazushiMe/Switch-OC-Suite/commit/d596016c841c32947867f84976ce4315f85f8ccc

Fixed in Oct 16th release: https://github.com/KazushiMe/Switch-OC-Suite/releases/tag/1.4.0.

**Comment by monstrosities** [comment]
Great work! It all looks good to me now, thanks again.
