### ISSUE TITLE
Mem clock up to 1996 even I turn off sys-clok-oc

### ISSUE THREAD

**Issue by knudalr** [KazushiMe/Switch-OC-Suite#35]
Deal all,
Emummc 14.1.1
Switch-OC-Suite:1.4.0 release
Atomsphere 1.4.0

TV mode:
step1: I set frequency for  game is 1785/921/1600. when I run game, it is normal as I wish.
Step2: But when I close game, frequency is 1020/768/1996.

Why mem clock is so high to 1996 with no APP profile setting .

at last , I found it in Github:
**_Safe:
Mariko: 1996.8 MHz has been tested stable for all (Samsung / Micron / Hynix), with built-in timing auto-adjustment._**

I don't understand "**_with built-in timing auto-adjustment_**.",  that mean sys-clk-oc will automatically increase the memory frequency to 1996, even if I haven't set it?

thanks for your kindly help.

**Comment by KazushiMe** [comment]
It is expected behavior. Default RAM frequency on dock is 1996.8 MHz, which is hard-coded in loader.kip.

To alter it, set Docked mode memory frequency in "Global profile" overlay.
