### ISSUE TITLE
auto boost issue 

### ISSUE THREAD

**Issue by dj5927** [KazushiMe/Switch-OC-Suite#36]
24 days update

There is a bug that always maintains 1785 when auto boost is used when a charger is connected.
If the charger is not connected, there is no problem.

switch lite  15.0 / ams 1.4.0

**Comment by dj5927** [comment]
Delete the old config.ini file
It works fine.

**Comment by KazushiMe** [comment]
Fixed on Oct 27th, see https://github.com/KazushiMe/Switch-OC-Suite/releases/tag/1.4.0.
