### ISSUE TITLE
PLZ support Erista Switch-OC-Suite

### ISSUE THREAD

**Issue by wyx3637338** [KazushiMe/Switch-OC-Suite#39]
Erista models request Switch-OC-Suite, specifically GPU1.3GHZ support

**Comment by KazushiMe** [comment]
Sys-clk-OC was updated to support Erista on Oct 29.
GPU of Erista variants only supports up to 921 MHz. Anything higher than 921 MHz is placebo.
CPU OC > 1785 MHz does not work out of the box, as this is considered extremely unsafe. Add missing entries into CPU cvb table and recompile loader and sys-clk, if you are seriously into this.
