### ISSUE TITLE
CPU&GPU dvfs coefficients and GPU overvolting

### ISSUE THREAD

**Issue by 3DSBricker** [KazushiMe/Switch-OC-Suite#4]
Hello,
On your previous repository I noticed some issues about 1344MHz not working. I have the same issue. Is there anything I can do about it or am I just out of luck? Mine goes up to 1305MHz. The CPU works fine up to 2.9GHz (just for short testing).

**Comment by KazushiMe** [comment]
I haven't looked into GPU related codes in pcv module actually. Those coefficients in GPU table are my guess, you can try investigating the assembly and changing them.

AFAIK there is no GPU benchmark homebrew (also quite difficult to make one), so you cannot tell if anything over 1267 MHz are effective or just placebo values by now. (Generating more heat is confirmed)

As for CPU, the limiting factor is voltage (cannot go up to 1.3V from my testing). 2.9GHz must be placebo as it requires at least 1.7V to runs at that clock steadily (~1130mV for 2295MHz and ~1220mV for 2397MHz).

I ported a [CPU frequency measurement utility](https://github.com/KazushiMe/mhz), where you will get real/effective clock rates.

**Comment by 3DSBricker** [comment]
I hope 1.7V is a typo... I can't go above 1305MHz no matter what. Is there some sort of 1344MHz limit in the code btw? I thought like, maybe 1344MHz just won't work with those coefficients. How would you guess them actually?

**Comment by KazushiMe** [comment]
GPU cvb pll table in patch.inc: https://github.com/KazushiMe/Switch-OC-Suite/blob/2755d7aec33169f4e7be4c17eda07c8e6362575b/Source/Atmosphere/ldr_oc_patch.inc#L93-L97

GPU CVB coefficients from L4T: https://github.com/yshr1982/jetson_nano_kernel/blob/fa0c7b06567245d04b1c83392e161aec7d88ec17/kernel/kernel-4.9/drivers/soc/tegra/tegra210-dvfs.c#L836

`set_gpu_dvfs_data()`:
https://github.com/yshr1982/jetson_nano_kernel/blob/fa0c7b06567245d04b1c83392e161aec7d88ec17/kernel/kernel-4.9/drivers/soc/tegra/tegra210-dvfs.c#L1882

Those coefficients are used to determine cvb_voltage and cvb_t_voltage:
https://github.com/yshr1982/jetson_nano_kernel/blob/fa0c7b06567245d04b1c83392e161aec7d88ec17/kernel/kernel-4.9/drivers/soc/tegra/cvb.c#L21
```c
/* cvb_mv = ((c2 * speedo / s_scale + c1) * speedo / s_scale + c0) */
int tegra_get_cvb_voltage(int speedo, int s_scale,
			  const struct cvb_coefficients *cvb)
{
	int mv;

	/* apply only speedo scale: output mv = cvb_mv * v_scale */
	mv = DIV_ROUND_CLOSEST(cvb->c2 * speedo, s_scale);
	mv = DIV_ROUND_CLOSEST((mv + cvb->c1) * speedo, s_scale) + cvb->c0;
	return mv;
}

/* cvb_t_mv =
   ((c3 * speedo / s_scale + c4 + c5 * T / t_scale) * T / t_scale) / v_scale */
int tegra_get_cvb_t_voltage(int speedo, int s_scale, int t, int t_scale,
			    struct cvb_coefficients *cvb)
{
	/* apply speedo & temperature scales: output mv = cvb_t_mv * v_scale */
	int mv;
	mv = DIV_ROUND_CLOSEST(cvb->c3 * speedo, s_scale) + cvb->c4 +
		DIV_ROUND_CLOSEST(cvb->c5 * t, t_scale);
	mv = DIV_ROUND_CLOSEST(mv * t, t_scale);
	return mv;
}
```

**Comment by Cooler3D** [comment]
Hello. The same issue. Mariko, Switch Lite, Samsung RAM.

**Comment by 3DSBricker** [comment]
Also an update on this. It's the coefficients. I find out that if I use the same coefficients from 1305 on those higher frequencies, it works. Coefficients are used to calculate Voltage so Voltage is the same, meaning it could get unstable. @KazushiMe is investigating/looking into this so just be patient. For now, I haven't seen any game benefiting, nor needing those high frequencies at all. There's not much gain.

**Comment by Cooler3D** [comment]
I have bunch of custom graphic mods, for games on id Tech, UE 4 and others. With higher freq on GPU (~1500), i think, 60 FPS without dynamic resolution can be achieved.

**Comment by Cooler3D** [comment]
> Also an update on this. It's the coefficients. I find out that if I use the same coefficients from 1305 on those higher frequencies, it works. Coefficients are used to calculate Voltage so Voltage is the same, meaning it could get unstable. @KazushiMe is investigating/looking into this so just be patient. For now, I haven't seen any game benefiting, nor needing those high frequencies at all. There's not much gain.

I have bunch of custom graphic mods, for games on id Tech, UE 4 and others. With higher freq on GPU in the future (~1500MHz), i think, 60 FPS without dynamic resolution can be achieved.

**Comment by 3DSBricker** [comment]
No, I really mean there's not much gain. First of all, there's a long road to 1500... Secondly, a higher the frequency ISN'T always better. There just won't be much gain in performance, not performance that's not needed, there just is none extra. Same with Erista, anything above 921MHz won't really give you any benefit. There's just more power draw, and thus more risk of damaging components. The CPU, for example, just won't give enough extra performance to make it worth the extra power above 2.4-2.6GHz.

**Comment by KazushiMe** [comment]
Found only one GPU voltage offset for now:
https://github.com/KazushiMe/Switch-OC-Suite/blob/8bd7fa6f99399066578ee5178fc940571bae71d3/Source/Atmosphere/stratosphere/loader/source/ldr_oc_patch.hpp#L100-L105

GPU coefficients:
https://github.com/KazushiMe/Switch-OC-Suite/blob/8bd7fa6f99399066578ee5178fc940571bae71d3/Source/Atmosphere/stratosphere/loader/source/ldr_oc_patch.hpp#L113-L128
Dynamic voltage scaling could be disabled for specific frequency by leaving `c1`-`c5` coefficients empty, then the voltage will stay @ `c0` uV. e.g.:
```cpp
{ 1305600, 0, {}, {  980000 } }, //  980 mV
{ 1344000, 0, {}, { 1000000 } }, // 1000 mV
{ 1382400, 0, {}, { 1020000 } }, // 1020 mV
{ 1420800, 0, {}, { 1040000 } }, // 1040 mV
{ 1459200, 0, {}, { 1060000 } }, // 1060 mV
{ 1497600, 0, {}, { 1080000 } }, // 1080 mV
{ 1536000, 0, {}, { 1100000 } }, // 1100 mV
```
Same for CPU coefficients: 
```cpp
{ 2397000, 0, { 1220000 }, { NewCpuVoltageScaled } }, // 1220 mV
```

If you somehow get some coefficients working stably, please report your `CPU Speedo 0 (CPU Val)` and `CPU Speedo 2 (GPU Val)` speedo values shown in Hekate `HW & Cached Fuses Info`, which proper dvfs voltage calculation requires.

**Comment by KazushiMe** [comment]
No issues so far, except for GPU not reaching anything higher than 1525 MHz. I don't see that could benefit overall experience as GPU is heavily limited by DRAM bandwidth.

**Comment by Cooler3D** [comment]
> No issues so far, except for GPU not reaching anything higher than 1525 MHz. I don't see that could benefit overall experience as GPU is heavily limited by DRAM bandwidth.

Confirmed from RU community.
