### ISSUE TITLE
mem speed reported incorrectly

### ISSUE THREAD

**Issue by ms2048** [KazushiMe/Switch-OC-Suite#4]
While it is nice of you to remove the options to change ram frequency in v1.2 (no point in setting these) there is still an issue with both Tesla overlay and sys-clk-manager reporting whatever ram frequency was there before or 1331.2 by default. This is definitely confusing. If this stat cannot be read correctly (I assume) maybe consider removing reporting it altogether? No information is better than wrong information...

**Comment by KazushiMe** [comment]
Thanks for reporting, it's a bug in the patcher script that ptm patch is not copied correctly. I've fixed it in the latest(May 30th) release.
You don't need to reapply the patch, just copy the folder `/atmosphere/oc_patches/12-patch/ptm-patch` to `/atmosphere/exefs_patches/`.

**Comment by ms2048** [comment]
thank you, confirmed fixed (via manual copying)
