### ISSUE TITLE
Bug with new feature governor per title

### ISSUE THREAD

**Issue by skydark719** [KazushiMe/Switch-OC-Suite#41]
There's an issue with this new feature, if a game or app is specifically disabled with that toggle, the clocks will be always 1020/307 on handheld mode (or 384 | 460 GPU, depends of the default frequency of the title without OC) and 1020/768 on docked mode. But if the governor option is globally disabled, this not happens.

Also, now screen backlight off doesn't work.

**Comment by dj5927** [comment]
I checked and it's the same symptoms.

If you turn off the governor function in the title, it seems that the sys-clk function itself is turned off.
