### ISSUE TITLE
Do i need to delete sysclk manager ? I got fatal error while running the newest one

### ISSUE THREAD

**Issue by timunkun** [KazushiMe/Switch-OC-Suite#42]
I don't know if it's because im still using the manager from the last update or something happen

**Comment by dj5927** [comment]
On the 29th update
The sys-clk.nro file seems to be missing.
please check.

Thanks always for the quick feedback.

**Comment by timunkun** [comment]
> On the 29th update The sys-clk.nro file seems to be missing. please check.
> 
> Thanks always for the quick feedback.

I use V2 mariko. But the sysclk is acting weird. Everytime i wanna change something like changing freq, turning on feature like governor and unsafe freq etc. It gives me fatal error.. here's some pict

![P_20221029_200743](https://user-images.githubusercontent.com/106679989/198833351-0b41d1a6-4a6c-45f3-af48-7742b1f75410.jpg)

![P_20221029_200751](https://user-images.githubusercontent.com/106679989/198833368-733af90b-6a05-422a-b6b9-d7cf41dd07ac.jpg)
![P_20221029_200822](https://user-images.githubusercontent.com/106679989/198833382-39e4af20-39be-4b7e-9506-db073542abef.jpg)

**Comment by timunkun** [comment]
Turns out it still the same even tho i deleted sysclk manager. Probably mew build borked for mariko

**Comment by KazushiMe** [comment]
The error code means sys-clk cannot save config.ini, check if this file is corrupted.

**Comment by willowdale16** [comment]
> The error code means sys-clk cannot save config.ini, check if this file is corrupted.
probably not, i already delete the config.ini and it's still the same, and then i revert it back to the last commit (oct 27th) with the same config.ini and it runs normally. so only new commit that borked. tested with 2 switches.

**Comment by timunkun** [comment]
> The error code means sys-clk cannot save config.ini, check if this file is corrupted.

probably not, i already delete the config.ini and it's still the same, and then i revert it back to the last commit (oct 27th) with the same config.ini and it runs normally. so only new commit that borked. tested with 2 switches.

**Comment by dj5927** [comment]
I am experiencing the same symptoms.

Marico Switch.

**Comment by KazushiMe** [comment]
My bad, sys-clk config path was changed along with the sysmodule target name. Hotfix uploaded: https://github.com/KazushiMe/Switch-OC-Suite/releases/download/1.4.0/SdOut.zip.

**Comment by dj5927** [comment]
Sorry to bother you.

After using the hotfix, the GPU cannot be overclocked above 460 in portable mode.

Also, the auto cpu boost function is turned off continuously.

Something is wrong.

**Comment by KazushiMe** [comment]
> After using the hotfix, the GPU cannot be overclocked above 460 in portable mode.
> Also, the auto cpu boost function is turned off continuously.

Can't reproduce the issue here. Could you upload full log `/config/sys-clk/log.txt`? If there is none, create an empty file named `log.flag` in `/config/sys-clk/`.

**Comment by dj5927** [comment]
> [2022-10-30 02:11:53.819] [mgr] TitleID change: 0240049B50312000
[2022-10-30 02:11:53.833] [mgr] CPU clock change: 1785.0 MHz
[2022-10-30 02:11:53.839] [mgr] GPU clock change: 76.8 MHz
[2022-10-30 02:11:54.498] [mgr] CPU clock change: 1020.0 MHz
[2022-10-30 02:11:54.505] [mgr] GPU clock change: 307.2 MHz
[2022-10-30 02:12:00.656] [cfg] Reading /config/sys-clk//config.ini
[2022-10-30 02:12:04.241] [cfg] Reading /config/sys-clk//config.ini
[2022-10-30 02:12:09.863] [cfg] Reading /config/sys-clk//config.ini
[2022-10-30 02:12:09.877] [mgr] Governor status: enabled
[2022-10-30 02:12:10.912] [cfg] Reading /config/sys-clk//config.ini
[2022-10-30 02:12:10.925] [mgr] Governor status: disabled
[2022-10-30 02:12:10.944] [mgr] GPU clock change: 307.2 MHz
[2022-10-30 02:12:19.095] [cfg] Reading /config/sys-clk//config.ini
[2022-10-30 02:12:19.121] [mgr] GPU clock set : 460.8 MHz
[2022-10-30 02:12:41.537] [mgr] TitleID change: 0100000000001000
[2022-10-30 02:12:41.642] [mgr] GPU clock change: 307.2 MHz



Created and tested now.

**Comment by dj5927** [comment]
handheld
GPU 460 max

docked
GPU 921 max

usb charger
GPU 768 max

More settings are not possible.

**Comment by KazushiMe** [comment]
Fixed wrong HardwareType cases, which caused Hoag(Lite) being detected as Erista.

**Comment by dj5927** [comment]
thank you

Almost everything has been fixed.

one last thing...

auto boost cpu disappeared from entry.

is this intentional?

**Comment by KazushiMe** [comment]
> auto boost cpu disappeared from entry.

Make sure sys-clk overlay is updated along with the sysmodule.

**Comment by dj5927** [comment]
![16670672214823309983684088515809](https://user-images.githubusercontent.com/73052093/198846807-61531db9-b76e-454e-b4c7-680af60d6988.jpg)


all updated
There is no auto boost item as in the screenshot.

**Comment by KazushiMe** [comment]
[sys-clk-overlay.ovl.zip](https://github.com/KazushiMe/Switch-OC-Suite/files/9894335/sys-clk-overlay.ovl.zip)
I might have messed up the release in .zip. See if this one works.

**Comment by KazushiMe** [comment]
Fixed. `spl:` service is unavailable in overlay, have to get hardware type via sysmodule ipc.

**Comment by monstrosities** [comment]
Calcio is mariko by the way, not that I imagine anyone uses Atmosphere on one!

**Comment by dj5927** [comment]
Now it's perfect.
Thank you.
