### ISSUE TITLE
Governor mode caps boost to 1785

### ISSUE THREAD

**Issue by pixeltester** [KazushiMe/Switch-OC-Suite#44]
Governor mode seems to cap boost mode to 1785 even if you've set up a higher one, could this be changed to use the user's boost?

**Comment by pixeltester** [comment]
Can I also ask if dropping below 1020MHz cpu with governor on mariko is worth it? Based on your own comment here: https://github.com/KazushiMe/Switch-OC-Suite/pull/12#issuecomment-1036560652

**Comment by pixeltester** [comment]
I did some more testing and I found that using a temporary override for cpu also caps boost mode at the temporary override cpu clock. I think the logic might have changed as the boost cpu setting always used to override any other settings. So would it be possible to have "marikoCpuBoostClock" always override other cpu settings?

**Comment by pixeltester** [comment]
For feedback:  The referenced commit didn't change the behavior, governor still limits boost to 1785.

**Comment by KazushiMe** [comment]
Falling back to configuration parsing, since I could not find a way to request performance mode within sysmodule.

Place loader.kip in one of these following directories:
- `/` (root)
- `/atmosphere/`
- `/atmosphere/kips/`
- `/bootloader/`

**Comment by pixeltester** [comment]
> Falling back to configuration parsing, since I could not find a way to request performance mode within sysmodule.
> 
> Place loader.kip in one of these following directories:
> 
> * `/` (root)
> * `/atmosphere/`
> * `/atmosphere/kips/`
> * `/bootloader/`

So it's expected behavior? The loader kip with the 2091 boost is in the correct location and the boost works outside of governor mode. I noticed within governor mode it can work for a second but then drops to 1785.
