### ISSUE TITLE
31 update new bug

### ISSUE THREAD

**Issue by dj5927** [KazushiMe/Switch-OC-Suite#47]
[2022-10-31 03:42:35.675] [mgr] Governor status: enabled
[2022-10-31 03:42:35.679] [!] ASSERT_RESULT_OK: threadCreate
  RC: [0x559] 0345-0002
[2022-10-31 03:42:35.692] Exit

After the 31st update, if you turn on the governor function only, clk becomes unavailable with the same error as the log.

Switch lite (hoag mariko) - retail

**Comment by monstrosities** [comment]
The new release does appear to be broken. I get the same as above in my log on a Switch OLED.

When I activate the governor the overlay shows a Fatal Error with `sysclkIpcGetCurrentContext [0xf601] 0001-0123`

**Comment by deathblade201243** [comment]
happens on Erista as well multiple different codes will appear for  "setprofiles" "setconfigvalues" "GetCurrentContext"

**Comment by renA21** [comment]
Thanks for the fix! But now the sysmodule crashes altogether when changing the config of a game with error 2168-0002 (0x4a8).

**Comment by dj5927** [comment]
thank you

It seems to be the most stable state out of the 1.4.0 version so far.

**Comment by dj5927** [comment]
2022-10-31 14:49:00.082] [mgr] CPU clock set : 1428.0 MHz
[2022-10-31 14:49:00.092] [mgr] Memory clock set : 1862.4 MHz
[2022-10-31 14:49:00.098] [mgr] Cannot set Memory clock to 1862.4 MHz



Is it normal for ram overclock to show up like this in the log?

Marico Switch.

**Comment by KazushiMe** [comment]
> Is it normal for ram overclock to show up like this in the log?

Fixed in https://github.com/KazushiMe/Switch-OC-Suite/commit/523d2dc45a576551934ae3d207439d7344580c0a
