### ISSUE TITLE
Governor and cpu boost

### ISSUE THREAD

**Issue by desconection** [KazushiMe/Switch-OC-Suite#49]
Governor mode seems to override cpu boost, if i set cpu boost to 1785 but use cpu higher than 1785mhz on any profile the boost exceeds 1785mhz on loading.

example: auto cpu boost is on 1785, governor is enabled and profile is set to 2091 cpu, on loading the governor will boost the cpu to 2091 overriding the 1785 from cpu boost

**Comment by pixeltester** [comment]
It's probably a side effect of the fix for this issue https://github.com/KazushiMe/Switch-OC-Suite/issues/44 where a higher boost setting was being overridden by the governor and reduced to 1785.

**Comment by KazushiMe** [comment]
This is expected. When a game requests boost mode, governor will set maximum available frequency `max(boostFreq, profileFreq)` for CPU regardlessly, while GPU retaining minimum frequency (76.8 MHz).
