### ISSUE TITLE
2131MHz MEM clock not possible anymore

### ISSUE THREAD

**Issue by TeleTubby666** [KazushiMe/Switch-OC-Suite#50]
Hi,

I used to run my OLED Switch on 2131 MHz MEM clock rock stable for months with an old version of Switch OC Suite.

![0BEB5CE9-88EC-47B1-9D69-ABB934C79ABA](https://user-images.githubusercontent.com/80608448/199179226-f285e71c-6f28-4a31-a111-f7ed31afc625.jpeg)

Now, that I am forced to use a recent AMS version I have to upgrade the suite as well. And now it seems the clocks are limited to 1996 MHz by editing the KIP file using the Python tool.

Am I doing something wrong nowadays or is it simply just not possible any more to clock the memory higher than 1996 MHz?

Thank you in advance!

**Comment by KazushiMe** [comment]
> Am I doing something wrong nowadays or is it simply just not possible any more to clock the memory higher than 1996 MHz?

To save any changes to loader.kip, `--save` argument is required.

$ ./ldr_config.py -h
usage: ldr_config.py [-h] [--save] [--ignore] file

Loader Configurator v2

positional arguments:
  file        Path of loader.kip

optional arguments:
  -h, --help  show this help message and exit
  **--save, -s  Save configuration to loader.kip**
  --ignore    Ignore range safety check

**Comment by TeleTubby666** [comment]
There seems to be another issue. I succeeded in to edit and save the kip file successfully:

> python ldr_config.py --save loader.kip
> Saving new configuration...
> - mtcConf              :        0 ->        1
> - marikoCpuMaxClock    :  2397000 ->  2193000
> - marikoCpuBoostClock  :  1785000 ->  2397000
> - marikoCpuMaxVolt     :     1220
> - marikoGpuMaxClock    :  1305600
> - marikoEmcMaxClock    :  1996800 ->  2131200
> - eristaCpuOCEnable    :        0
> - eristaCpuMaxVolt     :        0
> - eristaEmcMaxClock    :  1862400
> - eristaEmcVolt        :        0
> Done!

The resulting kip file is moved into the atmosphere's kips folder,

**Comment by TeleTubby666** [comment]
Problem is solved now:

kip1=atmosphere/kips/loader.kip must not be in the [config] section, it has to be in the individual section for emuMMC
