### ISSUE TITLE
Auto CPU Boost issue 

### ISSUE THREAD

**Issue by dj5927** [KazushiMe/Switch-OC-Suite#51]
Last updated on Nov 1st, 2022, build

Turning off auto CPU burst also seems to apply.

off but max cpu (1780) during max loading
It is powered by minimal gpu.

mariko switch

**Comment by pixeltester** [comment]
Unless I didn't understand your issue that sounds normal. Auto boost is for when the core is stressed and has nothing to do with official boost which behaves as expected.

**Comment by KazushiMe** [comment]
See README. Disabling Auto CPU Boost feature will not affect default game behavior - requesting boost mode from official ptm sysmodule.
