### ISSUE TITLE
Bug: Disable fast charging feature

### ISSUE THREAD

**Issue by Muzika** [KazushiMe/Switch-OC-Suite#56]
Does the feature disable fast charging not work or am I just misunderstanding its functionality? I tried setting it to on or off back and forth, Unplugging & reconnecting the charger and even trying to reboot the console but it doesn't seem to make any changes at all. I am monitoring every value I can see below the miscellaneous window on the bottom of sys-clk-oc and I still get 2000mAh on my third party charger and 1200mAh(or 1500mAh?) on the official charger and these values never change whether I have it on or off.

Update:

So this issue is only applicable to switch lite. I tried this on my OLED today and found out that it works! Does the switch lite have a different power IC than the OLED/Regular switch?

**Comment by KazushiMe** [comment]
Thanks for your feedback.

I guess it is the restriction from system side, as Lite don't support charging from Dock directly (slow charging @500mA).

Communicating with BMS IC BQ24193 might be an alternative - bringing in the ability to set any limit (512 - 4544 mA, ~2W to ~18W?) on battery charging current.

**Comment by Muzika** [comment]
I see. Well I don't have any knowledge how to do this though. I have no experience programming with HAL so I don't think I can contribute to implementing this feature. Heck I couldn't even find where Psm_DisableBatteryCharging & Psm_EnableBatteryCharging is coming from(tried checking atmosphere & hekate source codes to no avail) :p

I'm still happy as I can do limit charging on the console. Apparently it bypasses the battery whenever it hits the limit I set. This is golden specially with my switch lite case with built in battery bank. 

Thank you very much for this!

**Comment by KazushiMe** [comment]
Battery charging current slider has been added, see if it works for Lite. [1.4.0.1-pre](https://github.com/KazushiMe/Switch-OC-Suite/releases/tag/1.4.0.1)

**Comment by Muzika** [comment]
Wow cool! Just got back from new year vacation. Will try this one in a short while :)

Happy new year by the way!

**Comment by Muzika** [comment]
Update

It works perfectly! This is much much better than the previous option since you can literally fine tune the charging current. 

Thank you very much for the feature update! Highly appreciate it :)

Finally I can play my switch lite while on a charging case without having the PCB temperature going high :D
