### ISSUE TITLE
Suggestion: Bring back disable charging toggle 

### ISSUE THREAD

**Issue by Anxietytimmy** [KazushiMe/Switch-OC-Suite#57]
As the title suggests, the return of the disable charging toggle would be nice.

**Comment by Muzika** [comment]
If you're fine with it, I can create you a custom build with a disable charging toggle if you want?

**Comment by Muzika** [comment]
Here you go if you want. I was interested in this also so I built one for myself.

[Switch-OC-Suite with disable charging.zip](https://github.com/KazushiMe/Switch-OC-Suite/files/10301252/Switch-OC-Suite.with.disable.charging.zip)

**Comment by Muzika** [comment]
Source code changes
[disable_charging.patch](https://github.com/KazushiMe/Switch-OC-Suite/files/10301275/disable_charging.patch)

**Comment by timunkun** [comment]
> Here you go if you want. I was interested in this also so I built one for myself.
> 
> [Switch-OC-Suite with disable charging.zip](https://github.com/KazushiMe/Switch-OC-Suite/files/10301252/Switch-OC-Suite.with.disable.charging.zip)

Heyy, sorry for oot. Can u rebuild sysclk with a higher cpu freq ? (e.g 2499mhz) Thank you~

**Comment by KazushiMe** [comment]
[1.4.0.1](https://github.com/KazushiMe/Switch-OC-Suite/releases/tag/1.4.0.1)

Added a temporary toggle "Force disable charging" - will be reset once power state changes.
