### ISSUE TITLE
Can't work on HOS 13.2.0 and AMS 1.2.5

### ISSUE THREAD

**Issue by James-Makoto** [KazushiMe/Switch-OC-Suite#6]
OC-Suite can not work after installation. Confirmed that PTM-Patches and kips were deleted.
（From a guy you are chatting on QQ, banned this moring :( ）

**Comment by Cooler3D** [comment]
The same issue. AMS 1.2.5 / HOS 13.**1**.0

**Comment by MattyXarope** [comment]
Related: are people actively using this Switch-OC-Suite? I was under the impression it wasn't finished yet...

**Comment by 3DSBricker** [comment]
Binary is inside the source code. You have to download the whole code and everything is inside the SdOut folder.

**Comment by KazushiMe** [comment]
Option to set emc frequency in `oc.ini` will be postponed, fall back to "loader.kip" for now.
