### ISSUE TITLE
Suggestion : add Current Flow to Status Monitor Mini/Full

### ISSUE THREAD

**Issue by ChanseyIsTheBest** [KazushiMe/Switch-OC-Suite#66]
This would be useful to see how load on the processer (and its frequency) influences power draw and would let you play the game with the overlay up because right now you can't play the game with Info & Current flow stuff up. Might be a good idea to also show the precise battery life as well.

**Comment by lowburger** [comment]
Here is not a Status Monitor.

**Comment by ChanseyIsTheBest** [comment]
Oh crap I thought status monitor was included in Switch-OC-Suite while its not. Oops. Still hope its added in but that's for someone elses project
