### ISSUE TITLE
Erista with 1.4.1 wont boot

### ISSUE THREAD

**Issue by jack16683** [KazushiMe/Switch-OC-Suite#67]
Just tried 1.4.1 on Erista and it black screened after Atmosphere logo, replaced it with 1.4.0 and it worked fine.

**Comment by pixeltester** [comment]
Update atmosphere to 1.4.1 also.

**Comment by jack16683** [comment]
> 

I did have atmosphere 1.4.1. But I reinstalled atmosphere 1.4.1 and oc-suite 1.4.1 it works fine now. Not sure why but thank you.

**Comment by Anxietytimmy** [comment]
Same issue here, even without loader tweaks.

**Comment by KazushiMe** [comment]
There has been several silent updates in 1.4.1 (OC Suite and Atmosphere). Make sure to grab latest one from both repos. Re-open the issue if the problem persists.
