### ISSUE TITLE
Unsafe toggle missing

### ISSUE THREAD

**Issue by pixeltester** [KazushiMe/Switch-OC-Suite#68]
Was it intentional to fully remove the unsafe frequency toggle from the overlay in recent versions? Seemed like a useful thing to have.

I saw that it's still in the readme and the only edit was to say that it's not for Mariko only any longer but I don't see it on Erista or Mariko https://github.com/KazushiMe/Switch-OC-Suite/commit/f47e7604fee263adcd3dcbb7648d42126352f68f#diff-5cc51a193535e4b290d081aacc31d388ced182468e7319b43050c2619076a3b2

**Comment by KazushiMe** [comment]
The GUI toggle is removed by design to make sure user has read [FAQs](https://kazushime.github.io/Switch-OC-Suite/#faq) before usage.
