### ISSUE TITLE
Switch-OC-Suite not working :/

### ISSUE THREAD

**Issue by musli64** [KazushiMe/Switch-OC-Suite#7]
Hello 
I have erista and install put everything on sd card 
I open sys clock and i see frequency cpu gpu 
Change to more than 1785 
example 2295 and gpu more than 921 
and click ok 
I see is ok 
but if i play the game Doom or another i dont see any change on status monitor overlay
Max 1795 cpu and gpu 921 

Atmos 0.19.2 
Os 12.01 

And ram Max frequency is 1600mhz 

Please help me :)

**Comment by KazushiMe** [comment]
Have you read the instruction section in README and applied pcv module patch? OC won't work if you only copy these files to SD card.

**Comment by musli64** [comment]
Yes 
I applied pcv :)
