### ISSUE TITLE
one problem with patch

### ISSUE THREAD

**Issue by musli64** [KazushiMe/Switch-OC-Suite#8]
cp -R ~/Switch-OC-Suite/Atmosphere/*pp stratosphere/loader/source/
patch < ~/Switch-OC-Suite/Atmosphere/ldr_patcher.diff
I tray and i have 

$ patch < ~/Switch-OC-Suite/Atmosphere/ldr_patcher.diff
can't find file to patch at input line 3
Perhaps you should have used the -p or --strip option?
The text leading up to this was:
--------------------------
|--- stratosphere/loader/source/ldr_patcher.cpp @a672917
|+++ stratosphere/loader/source/ldr_patcher.cpp
--------------------------
File to patch:

What i must to do 

thank you

**Comment by KazushiMe** [comment]
Please note that these shell commands won't work out of the box, only to give an idea about which files to patch.

In your case, you're supposed to run `patch < ....diff` where your current working directory is the root of ams repo.
