### ISSUE TITLE
switch wont boot 

### ISSUE THREAD

**Issue by musli64** [KazushiMe/Switch-OC-Suite#9]
Please help me i have a problem 
i use patcher sysmmc.te and switch wont boot 
ofc and cfw

but if i wana reverse i have in tegraexplorer 
youre not using targeted horizon os version 
i dont have 12-patch.bak 

Please a file and what i must to do maybe version Switch-OC-Suite-v1.2-5.30? 
thank you

**Comment by KazushiMe** [comment]
I guess you are the one who DM me on discord the other day. Resolved.
